[package]
name = "spawn-child"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = { version = "0.15.3", features = ["ckb2023"] }

[features]
native-simulator = ["ckb-std/native-simulator"]

