[package]
name = "spawn-child"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.15.3"
spawn_cmd = { path = "../../libs/spawn_cmd" }

[features]
native-simulator = ["ckb-std/native-simulator"]

